### ISSUE TITLE
invalid URL escape "%na" (auch Standard Config)

### ISSUE THREAD

**Issue by J-A-U** [andig/ingress#1]
`./bin/ingress -c config.yml -d`

FATA[2019-01-20 14:32:31] parse https://demo.volkszaehler.org/middleware.php/data/%name%.json: invalid URL escape "%na"  trgt=vz

[config.yml.txt](https://github.com/andig/ingress/files/2776649/config.yml.txt)

**Comment by andig** [comment]
Ursache ist klar, fix dauert noch etwas. Fürs erste per git zurück.

**Comment by andig** [comment]
Fixed in master. The escape character has changed from % to @ to make this work.
